    <project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <!-- 1. Información del Proyecto -->
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.juanjomerchante</groupId>
    <artifactId>pajareria</artifactId>
    <version>1.0.0</version>
    <packaging>jar</packaging>

    <!-- 2. Propiedades y Configuración -->
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
    </properties>

    <!-- 3. Dependencias -->
    <dependencies>
        <!-- JUnit 5 (Júpiter) para Testing -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>5.10.0</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>

  